<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * About Controller
 *
 * @property \App\Model\Table\AboutTable $About
 *
 * @method \App\Model\Entity\About[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AboutController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('About');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => '5'
        ];
        $about = $this->paginate($this->About->find()->order(['id' => 'DESC']));
        $this->set(compact('about'));
    }

    public function add()
    {
        $about = $this->About->newEntity();
        if ($this->request->is('post')) {
            $input['title'] = $this->getRequest()->getData('title');
            $input['content'] = $this->getRequest()->getData('content');
            $input['creator'] = $this->getRequest()->getData('creator');
            $input['status'] = $this->getRequest()->getData('status');
            $this->About->patchEntity($about, $input);

            if ($this->About->save($about)) {
                return $this->redirect(['controller' => 'About', 'action' => 'index']);
            } else {
                $error = $about->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('about'));
    }

    public function edit()
    {
        $id = $this->request->getParam('id');
        $about = $this->About->get($id);
        $this->set('about', $about);
        if ($this->request->is('post')) {
            $input['title'] = $this->getRequest()->getData('title');
            $input['content'] = $this->getRequest()->getData('content');
            $input['creator'] = $this->getRequest()->getData('creator');
            $input['status'] = $this->getRequest()->getData('status');
            $this->About->patchEntity($about, $input);

            if ($this->About->save($about)) {
                return $this->redirect(['controller' => 'About', 'action' => 'index']);
            } else {
                $error = $about->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('about'));
    }

    public function delete()
    {
        $id = $this->request->getParam('id');
        $about = $this->About->get($id);
        $this->About->delete($about);
        return $this->redirect(['controller'=>'About','action' => 'index']);
    }

    public function search()
    {
        $search = $this->request->getQuery('q');
        $this->paginate = [
            'limit' => '3'
        ];
        $about = $this->paginate($this->About->find()->where(function ($exp, $query) use ($search) {
            return $exp->like('title', '%' . $search . '%');

        }));
        $this->set('about', $about);
    }
}
