<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Blogs Controller
 *
 * @property \App\Model\Table\BlogsTable $Blogs
 *
 * @method \App\Model\Entity\Blog[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class BlogsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Blogs');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => 5
        ];
        $blogs = $this->paginate($this->Blogs->find()->order(['id' => 'DESC']));
        $this->set(compact('blogs'));
    }

    public function add()
    {
        $blogs = $this->Blogs->newEntity();
        if ($this->request->is('post')) {
            $input['title'] = $this->getRequest()->getData('title');
            $input['description'] = $this->getRequest()->getData('description');
            $input['content'] = $this->getRequest()->getData('content');
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName =  $image_name.time() . "_" . rand(000000, 999999);
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $blogs->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Blogs->patchEntity($blogs, $input);
            if ($this->Blogs->save($blogs)) {
                $this->set(compact('blogs'));
                return $this->redirect(['controller' => 'Blogs', 'action' => 'index']);
            } else {
                $error = $blogs->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('blogs'));
    }

    public function edit()
    {
        $id = $this->request->getParam('id');
        $blogs = $this->Blogs->get($id);
        $this->set('blogs', $blogs);
        if ($this->request->is('post')) {
            $input['title'] = $this->getRequest()->getData('title');
            $input['description'] = $this->getRequest()->getData('description');
            $input['content'] = $this->getRequest()->getData('content');
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999) . $image_name;
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $blogs->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Blogs->patchEntity($blogs, $input);
            if ($this->Blogs->save($blogs)) {
                $this->set(compact('blogs'));
                return $this->redirect(['controller' => 'Blogs', 'action' => 'index']);
            } else {
                $error = $blogs->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('blogs'));
    }

    public function delete()
    {
        $id = $this->request->getParam('id');
        $blogs = $this->Blogs->get($id);
        $this->Blogs->delete($blogs);
        return $this->redirect(['controller' => 'Blogs', 'action' => 'index']);
    }

    public function search()
    {
        $search = $this->request->getQuery('q');
        $this->paginate = [
            'limit' => '3'
        ];
        $blogs = $this->paginate($this->Blogs->find()->where(function ($exp, $query) use ($search) {
            return $exp->like('title', '%' . $search . '%');
        }));
        $this->set('blogs', $blogs);
        $this->set('search', $search);
    }
}
