<?php
namespace App\Controller;

use App\Controller\AppController;


class CategoriesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Categories');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => '5'
        ];
        $cate = $this->paginate($this->Categories->find()->where(['parent_id'=>0])->order(['id' => 'DESC']));
        $this->set(compact('cate'));
    }

    public function add()
    {

    }

    public function edit($id = null)
    {

    }

    public function delete($id = null)
    {

    }
}
