<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * ContactClient Controller
 *
 *
 * @method \App\Model\Entity\ContactClient[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ContactClientController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//     $this->viewBuilder()->getLayout("fontendefault");
        $this->viewBuilder()->setLayout("fontendefault");
        $this->loadModel('Logo');
        $this->loadModel('Slider');
        $this->loadModel('Represent');
        $this->loadModel('Categories');
        $this->loadModel('Products');
        $this->loadModel('Shopon');
        $this->loadModel('Logolast');
        $this->loadModel('Usersclient');
        $this->loadModel('Contact');
    }


  public function contactt(){
      $contact = $this->Contact->find()
          ->select(['id', 'addr', 'phone', 'email', 'status'])
          ->where(['status' => 1])
          ->limit(1)
          ->order(['id' => 'DESC'])->toArray();

      $this->set('contact', $contact);
  }
    public function contact()
    {
        $this->logo();
        $this->slider();
        $this->represent();
        $this->title();
        $this->logolast();
        $this->users();
        $this->loginclient();
        $this->contactt();
        $this->menu();
        $this->showMenu();
    }
}
