<?php

namespace App\Http\Session;

namespace App\Controller;

use Cake\Event\Event;
use Cake\Cache\Cache;
use App\Controller\AppController;
use Cake\Http\Session;
use Symfony\Component\VarDumper\Dumper\DataDumperInterface;
use function mysql_xdevapi\getSession;

use Cake\Core\Configure;
use Cake\Http\Session\DatabaseSession;

class DetailClientController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//     $this->viewBuilder()->getLayout("fontendefault");
        $this->viewBuilder()->setLayout("cartfontend");
        $this->loadModel('Logo');
        $this->loadModel('Slider');
        $this->loadModel('Represent');
        $this->loadModel('Categories');
        $this->loadModel('Products');
        $this->loadModel('Shopon');
        $this->loadModel('Logolast');
        $this->loadModel('Usersclient');
        $this->loadModel('Contact');
    }

    public function logo()
    {
        $logo = $this->Logo
            ->find()
            ->select('image', 'link')
            ->where(['status' => 1]);
        $this->set(compact('logo'));
    }

    public function slider()
    {
        $slider = $this->Slider
            ->find()
            ->select(['name', 'link', 'image', 'text', 'id'])
            ->where(['status' => 1])
            ->limit(1);

        $this->set(compact('slider'));
    }

    //dai dien
    public function represent()
    {
        $represent = $this->Represent
            ->find()
            ->select(['name', 'image', 'status'])
            ->where(['status' => 1])
            ->limit(3)
            ->order(['id' => 'DESC']);
        $this->set(compact('represent'));
    }

    //products-title
    public function title()
    {
        $title = $this->Categories
            ->find()
            ->select(['id', 'name', 'parent_id', 'slug'])
            ->where(['status' => 1])
            ->limit(4)
            ->order(['id' => 'DESC']);
        $this->set(compact('title'));
    }

    //$logolast
    public function logolast()
    {
        $logolast = $this->Logolast->find()
            ->select(['id', 'link', 'image', 'text', 'status'])
            ->where(['status' => 1])
            ->limit(1)
            ->order(['id' => 'DESC'])->toArray();
        $this->set('logolast', $logolast);
    }

    // dang ki trang client
    public function users()
    {
        $users = $this->Usersclient->newEntity();
        if ($this->request->is('post')) {
            $input['name'] = $this->getRequest()->getData('name');
            $input['email'] = $this->getRequest()->getData('email');
            $input['password'] = md5($this->getRequest()->getData('password'));
            $this->Usersclient->patchEntity($users, $input);
            if ($this->Usersclient->save($users)) {
                $this->set(compact('users'));
                $this->Flash->success(__('ok'));
            } else {
                $error = $users->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('users'));
    }

    //login client
    public function loginclient()
    {
        if (isset($_POST['submit'])) {
            $email = $_POST['email'];
            $password = $_POST['password'];
            $userr = $this->Usersclient->find()
                ->select(['id', 'name', 'email', 'password'])
                ->where(['email' => $email])
                ->orwhere(['password' => $password])
                ->all()->toArray();
            $showEmail = $userr[0];
            $this->set('showEmail', $showEmail);
        }
    }

    public function detaill()
    {
        $id = $this->request->getParam('id');
//        $products = $this->Products->find()
//            ->select(['id', 'image', 'product_name', 'price', 'sale', 'description', 'size'])
//            ->where(['id' => 23])
//            ->first()->toArray();
        $products = $this->Products->get($id);
        $this->set('products', $products);

//        $relate = $this->Products->find()

        $relate = $this->Products->find()
            ->where(['id'])
            ->order(['id' => 'DESC'])
            ->limit(4)
            ->toArray();
        $this->set('relate', $relate);
//        dd($products);
    }

    public function addToCart()
    {
//        $this->getRequest()->getSession()->delete('cart');
        $id = $this->request->getParam('id');
        $product = $this->Products->get($id);
        if (!empty($product)) {
            //get gio hang hien tai
            if ($this->getRequest()->getSession()->check('cart')) {
                $dataCart = $this->getRequest()->getSession()->read('cart');
            } else {
                $dataCart = array();
            }
            if (empty($dataCart)) {
                $dataCart[count($dataCart)] = array(
                    'id' => $product['id'],
                    'name' => $product['product_name'],
                    'sale' => $product['sale'],
                    'slug' => $product['slug'],
                    'image' => $product['image'],
                    'quantity' => 1,
                );
            } else {
                $flg_new = true;
                $iUpdate = 0;
                for ($i = 0; $i < count($dataCart); $i++) {
                    if ($dataCart[$i]['id'] == $id) {
                        $flg_new = false;
                        $iUpdate = $i;
                        break;
                    }
                }
                if ($flg_new) {
                    $dataCart[count($dataCart)] = array(
                        'id' => $product['id'],
                        'name' => $product['product_name'],
                        'sale' => $product['sale'],
                        'slug' => $product['slug'],
                        'image' => $product['image'],
                        'quantity' => 1,
                    );
                } else {
                    $dataCart[$iUpdate]['quantity'] += 1;
                }
            }

            //check gio hang neu co roi thi them so luong, chua co the them moi

            //thuc hien add them san pham vao gio

            //            );
            //            dd($item);
            //tao gio hang va them san phamm vao trong gio hang
            //tao session
//            Cache::write('cart',$dataCart);
//            $session = $this->getRequest()->getSession();

            $this->getRequest()->getSession()->write('cart', $dataCart);
            //$this->getRequest()->getSession()->setFlash('Add thanh cong', 'default', array('class' => 'alert alert-info'), 'cart');
//            $this->redirect($this->referer());
//            pr($this->getRequest()->getSession()->read('cart'));
            $cart = $this->getRequest()->getSession()->read('cart');
//            dd($dataCart[$iUpdate]['quantity']);

            $total = 0;
            foreach ($cart as $product) {
//                dd($dataCart[$iUpdate]['quantity']);
//                dd($product['quantity']);
                $total += $product['quantity'] * $product['sale'];
            }
            $this->getRequest()->getSession()->write('total', $total);
            $this->set(compact('total'));
//            $this->redirect('cart');
        } else {
            echo 'sai id';
        }
//        $this->redirect($this->referer());
    }

    public function viewCart()
    {
//        $this->viewBuilder()->setLayout('cartfontend');
        $this->logo();
        $this->slider();
        $this->represent();
        $this->title();
        $this->logolast();
        $this->users();
        $this->loginclient();
//        $this->addToCart();

        $cart = $this->getRequest()->getSession()->read('cart');
//dd($cart);

        $total = 0;
        foreach ($cart as $product) {
//                dd($dataCart[$iUpdate]['quantity']);
//                dd($product['quantity']);
            $total += $product['quantity'] * $product['sale'];
        }

        $this->getRequest()->getSession()->write('total', $total);
        $this->set(compact('total'));
        $this->set(compact('cart'));

//        dd($totall);

        $payment = $this->getRequest()->getSession()->read('payment');
//      dd($payment);
        $this->set(compact('cart', 'payment'));
    }

    public function emptycart()
    {
        $this->getRequest()->getSession()->delete('cart');
        $this->getRequest()->getSession()->delete('total');
        $this->getRequest()->getSession()->delete('payment');
        $this->redirect($this->referer());
    }

    public function remove()
    {
        $id = $this->request->getParam('id');
//        $this->getRequest()->getSession()->delete('cart.' . $id);
//        dd($_SESSION['cart']);
        $cart = $this->getRequest()->getSession()->read('cart');
        foreach ($_SESSION['cart'] as $key => $value) {
//            dd($value['id']);
            if ($value['id'] == $id) {
                unset($_SESSION['cart'][$key]);
            }
        }

        if (empty($cart)) {
            $this->emptycart();
        } else {
            $total = 0;
            foreach ($cart as $product) {
//                dd($dataCart[$iUpdate]['quantity']);
//                dd($product['quantity']);
                $total += $product['quantity'] * $product['sale'];
                $this->getRequest()->getSession()->write('total', $total);
            }
            $this->redirect($this->referer());
        }
    }

    public function updatecart()
    {
        $cart = $this->getRequest()->getSession()->read('cart');
        dd($cart);
        $this->redirect('cart');
    }

    public function detail()
    {
        $this->logo();
        $this->slider();
        $this->represent();
        $this->title();
        $this->logolast();
        $this->users();
        $this->loginclient();
        $this->detaill();
        $this->addToCart();
        $this->viewCart();
    }
}
