<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Logo Controller
 *
 * @property \App\Model\Table\LogoTable $Logo
 *
 * @method \App\Model\Entity\Logo[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class LogoController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Logo');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => '5'
        ];
        $logo = $this->paginate($this->Logo->find()->order(['id' => 'DESC']));
        $this->set(compact('logo'));
    }

    public function add()
    {
        $logo = $this->Logo->newEntity();
        if ($this->request->is('post')) {
            $input['link'] = $this->getRequest()->getData('link');
            $input['text'] = $this->getRequest()->getData('text');
            $input['status'] = $this->getRequest()->getData('status');
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999) . $image_name;
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $logo->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Logo->patchEntity($logo, $input);
            if ($this->Logo->save($logo)) {
                $this->set(compact('logo'));
                return $this->redirect(['controller' => 'Logo', 'action' => 'index']);
            } else {
                $error = $logo->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('logo'));
    }

    public function edit()
    {
        $id = $this->request->getParam('id');
        $logo = $this->Logo->get($id);
        $this->set('logo', $logo);
        if ($this->request->is('post')) {
            $input['link'] = $this->getRequest()->getData('link');
            $input['status'] = $this->getRequest()->getData('status');
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999) . $image_name;
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $logo->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Logo->patchEntity($logo, $input);
            if ($this->Logo->save($logo)) {
                $this->set(compact('logo'));
                return $this->redirect(['controller' => 'Logo', 'action' => 'index']);
            } else {
                $error = $logo->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('logo'));
    }

    public function delete()
    {
        $id = $this->request->getParam('id');
        $logo = $this->Logo->get($id);
        $this->Logo->delete($logo);
        return $this->redirect(['controller' => 'Logo', 'action' => 'index']);
    }


    public function search()
    {
        $search = $this->request->getQuery('q');
        $this->paginate = [
            'limit' => '3'
        ];

        $logo = $this->paginate($this->Logo->find()->where(function ($exp, $query) use ($search) {
            return $exp->like('link', '%' . $search . '%');
        }));
        $this->set('logo', $logo);
        $this->set('search', $search);
    }
}
