<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Logo Controller
 *
 * @property \App\Model\Table\LogoTable $Logo
 *
 * @method \App\Model\Entity\Logo[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class LogoFontendController extends AppController
{
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Logo');
        $this->viewBuilder()->setLayout('fontendefault');
    }

    public function show()
    {
        $logo = $this->Logo->select(['image', 'link'])->where(['status' => 0]);
            $this->set(compact('logo'));

    }
}
