<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Orders Controller
 *
 * @property \App\Model\Table\OrdersTable $Orders
 *
 * @method \App\Model\Entity\Order[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class OrdersController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Orders');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => '5'
        ];
        $orders = $this->paginate($this->Orders->find()->order(['id' => 'DESC']));
        $this->set(compact('orders'));
    }
    public function search()
    {
        $search = $this->request->getQuery('q');
        $this->paginate = [
            'limit' => '5'
        ];

        $orders = $this->paginate($this->Orders->find()->where(function ($exp, $query) use ($search) {
            return $exp->like('link', '%' . $search . '%');
        }));
//        $this->set('orders', $orders);
        $this->set(compact('orders'));
        $this->set('search', $search);
    }
}
