<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */

namespace App\Controller\Component;

namespace App\Controller;


use App\Controller\Component\ToolComponent;
use Cake\Controller\Component;
use Cake\Cache\Cache;
use Cake\Datasource\EntityInterface;
use Cake\Http\Session\DatabaseSession;
use App\Model\Entity\Slider;
use Cake\Core\Configure;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use Cake\Auth\DefaultPasswordHasher;
use Symfony\Component\VarDumper\Dumper\DataDumperInterface;
use Cake\Mailer\MailerAwareTrait;

/**
 * Static content controller
 *
 * This controller will render views from Template/Pages/
 *
 * @link https://book.cakephp.org/3.0/en/controllers/pages-controller.html
 */
class PagesController extends AppController
{
    use MailerAwareTrait;
    public $components = [
        'Tool',
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//     $this->viewBuilder()->getLayout("fontendefault");
        $this->viewBuilder()->setLayout("fontendefault");
        $this->loadModel('Logo');
        $this->loadModel('Slider');
        $this->loadModel('Represent');
        $this->loadModel('Categories');
        $this->loadModel('Products');
        $this->loadModel('Shopon');
        $this->loadModel('Logolast');
        $this->loadModel('Usersclient');
        $this->loadModel('Contact');
    }

    public function display(...$path)
    {
        $count = count($path);
        if (!$count) {
            return $this->redirect('/');
        }
        if (in_array('..', $path, true) || in_array('.', $path, true)) {
            throw new ForbiddenException();
        }
        $page = $subpage = null;

        if (!empty($path[0])) {
            $page = $path[0];
        }
        if (!empty($path[1])) {
            $subpage = $path[1];
        }
        $this->set(compact('page', 'subpage'));

        try {
            $this->render(implode('/', $path));
        } catch (MissingTemplateException $exception) {
            if (Configure::read('debug')) {
                throw $exception;
            }
            throw new NotFoundException();
        }
    }

    public function menuMini()
    {
        $id = $this->request->getParam('id');
//        dd($id);
        $menuMinii = $this->Categories->find()
            ->select(['id', 'name', 'parent_id', 'status'])
            ->where(['status' => 1])
            ->andWhere(['parent_id' => 0])->toArray();
        $this->set(compact('menuMinii'));
//        dd($menuMinii);
    }

    public function products()
    {
        //products
        $products = $this->Products->find()
            ->select(['id', 'product_name', 'image', 'price', 'sale', 'description', 'size', 'slug', 'categories_id', 'status'])
            ->where(['status' => 1])
            ->andwhere(['categories_id' => 24])
            ->limit(8)
            ->order(['id' => 'ASC'])->toArray();
        $this->set('products', $products);
    }

    public function forgot()
    {
        $this->viewBuilder()->setLayout('forgot');
        $this->logo();
        $this->logolast();
//        $email = $this->Usersclient->find()
//            ->select(['id', 'name', 'email', 'password'])->toArray();
//        dd($emaill);
        $email = $this->Usersclient->newEntity();
//        dd($this->getRequest()->getData(['email']));
        if ($this->request->is('post')) {
            $user = $this->Usersclient->findByEmail($this->getRequest()->getData(['email']))->first();
//            dd($user->email);
//            dd($user);
            if (!empty($user)) {
//                dd(1);

                $code = $this->getRequest()->getData('code');
//                dd($code);
                //tao link xac thuc
//                $link_confirm = 'http://localhost:8765/confirm/' . $code;
                //luu ma xax nhan vao trong csdl
                $id = $this->Usersclient->id = $user['id'];
                $code = $this->Tool->generate_code($id);
//                dd( $this->Usersclient->id);
                $query = $this->Usersclient->query();
                $query->update()
                    ->set([
                        'code' => $code,
                    ])
                    ->where(['id' => $this->Usersclient->id])
                    ->execute();
//                dd($query);
//                dd($code);
                $this->getMailer('Usersclient')->send('testEmail', [$user]);
//                dd($this->getMailer('Usersclient')->send('testEmail',[$user]));
//                $this->Flash->success("Vui lòng kiểm tra Email" . $link_confirm);
            } else {
//                echo "Email ban nhập không đúng";
                $this->Flash->error("Email này chưa được đăng kí.Vui lòng nhập đúng Email");
            }
        }

    }

    //xac nhan mat khau
    public function confirm($code = null)
    {
//        dd($code);
        $this->viewBuilder()->setLayout('forgot');
        $this->logo();
        $this->logolast();
        $confirm = false;
//        dd($confirm);
//        dd($code);
        if (!empty($code)) {
            $user = $this->Usersclient->findByCode($code);
            $codee = $this->request->getParam('code');
            $password=md5($this->getRequest()->getData('password'));
            if (!empty($user)) {
                $confirm = true;
                $query = $this->Usersclient->query();
                $query->update()
                    ->set(['password' => $password])
                    ->where(['code'=>$codee])
                    ->execute();
//                $this->redirect('http://localhost:8765');
            }
        }
        $this->set('confirm', $confirm);
    }

    public function index()
    {
        $this->logo();
        $this->slider();
        $this->represent();
        $this->title();
        $this->products();
        $this->shopon();
        $this->logolast();
        $this->users();
        $this->loginclient();
        $this->menu();
        $this->menuMini();
        $this->showMenu();
    }
}
