<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * Represent Controller
 *
 * @property \App\Model\Table\RepresentTable $Represent
 *
 * @method \App\Model\Entity\Represent[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class RepresentController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('represent');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => 5
        ];
        $represent = $this->paginate($this->Represent->find()->order(['id' => 'DESC']));
        $this->set(compact('represent'));
    }

    public function add()
    {
        $represent = $this->Represent->newEntity();
        if ($this->request->is('post')) {
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999) . $image_name;
            $input['name'] = $this->getRequest()->getData('name');
            $input['status'] = $this->getRequest()->getData('status');
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $represent->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Represent->patchEntity($represent, $input);
            if ($this->Represent->save($represent)) {
                $this->set(compact('represent'));
                return $this->redirect(['controller' => 'Represent', 'action' => 'index']);
            } else {
                $error = $represent->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('represent'));

    }

    public function edit()
    {
        $id = $this->request->getParam('id');
        $represent = $this->Represent->get($id);
        $this->set('represent', $represent);
        $represent = $this->Represent->newEntity();
        if ($this->request->is('post')) {
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999) . $image_name;
            $input['name'] = $this->getRequest()->getData('name');
            $input['status'] = $this->getRequest()->getData('status');
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName)) {
                $represent->image = $uploaded_path . "/" . $setNewFileName;
            }
            $this->Represent->patchEntity($represent, $input);
            if ($this->Represent->save($represent)) {
                $this->set(compact('represent'));
                return $this->redirect(['controller' => 'Represent', 'action' => 'index']);
            } else {
                $error = $represent->getErrors();
                $this->set('err', $error);
            }
        }
        $this->set(compact('represent'));
    }

    public function delete()
    {
        $id = $this->request->getParam('id');
        $represent = $this->Represent->get($id);
        $this->Represent->delete($represent);
        return $this->redirect(['controller' => 'Represent', 'action' => 'index']);
    }
    public function search()
    {
        $search = $this->request->getQuery('q');
        $this->paginate = [
            'limit' => '3'
        ];

        $represent = $this->paginate($this->Represent->find()->where(function ($exp, $query) use ($search) {
            return $exp->like('name', '%' . $search . '%');
        }));
        $this->set('represent', $represent);
        $this->set('search', $search);
    }
}
