<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\Slider;

/**
 * Slider Controller
 *
 * @property \App\Model\Table\SliderTable $Slider
 *
 * @method \App\Model\Entity\Slider[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class SliderController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Silder');
    }

    public function index()
    {
        $this->paginate = [
            'limit' => 5
        ];
        $slider = $this->paginate($this->Slider->find()->order(['id' => 'DESC']));
        $this->set(compact('slider'));
    }

    public function add()
    {
        $slider = $this->Slider->newEntity();
        if ($this->request->is('post')) {
            $uploaded_path = "/img/upload";
            $tmp_name = $this->request->getData()['file']['tmp_name'];
//            dd($tmp_name);
            $image_name = $this->request->getData()['file']['name'];
            $setNewFileName = time() . "_" . rand(000000, 999999);
//            dd($image_name);
            if (move_uploaded_file($tmp_name, WWW_ROOT . $uploaded_path . "/" . $setNewFileName . $image_name)) {

                $input['name'] = $this->getRequest()->getData('name');
                $input['link'] = $this->getRequest()->getData('link');
                $input['text'] = $this->getRequest()->getData('text');
                $input['status'] = $this->getRequest()->getData('status');
                $slider->image = $uploaded_path . "/" . $image_name;
                $this->Slider->patchEntity($slider, $input);
//                dd($slider);
                if ($this->Slider->save($slider)) {

                    $this->set(compact('slider'));
                    return $this->redirect(['controller' => 'Slider', 'action' => 'index']);
                } else {
                    $error = $slider->errors();
                    $this->set('err', $error);
                }
            }
            $this->set(compact('slider'));
        }
    }

    public function edit()
    {

    }

    public function delete()
    {

    }
}
